### ISSUE TITLE
I was not able to get pass the login or register 

### ISSUE THREAD

**Issue by paulscliu** [whyhankee/scatter#2]
When I try to test the scatter, I have problem login.
I follow the instruction:
npm install
npm run reload

I found out that I have to set NODE_ENV= prod
then the server will start
when I try to register/login, I found that "serverUrl" in register.js/login.js is not defined.

**Comment by whyhankee** [comment]
hey, thanks for the interest in our little project.
Unfortunately we are in the process of rewriting parts of the stack and it's really not usable now.

I will update the README to reflect this
Sorry i cannot help you further at this point, check back later for updates.

Thanks!
